# 공통 프로퍼티
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      naming:
        physical-strategy: aladdin.kaineus.what2eat.global.util.PhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true
