# LOCAL(DEFAULT)
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:p6spy:h2:tcp://localhost/~/what2eat;
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: na
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
  output:
    ansi:
      enabled: always


logging:
  level: # 적용할 곳과 레벨을 지정합니다.
    p6spy: DEBUG
    root: WARN # TRACE 하면 value 나오긴 하는데 너무 많은 정보가 나온다...
    org:
      hibernate:
        SQL: ERROR
        type: ERROR
  logback:
    rollingpolicy:
      file-name-pattern: C:/logs/basic/%d{yyyy-MM-dd}_%i.gz
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss}:%-4relative] [%thread] %-5level %logger{35} - %msg%n"

hibernate:
  show_sql: false

log4j:
  logger:
    org:
      hibernate: ERROR